language: node_js
node_js:
- node
- '6.9'
- '5.11'
- '0.12'
- '0.10'
before_deploy:
- git config --global user.email "andersems@gmail.com"
- git config --global user.name "Anders Emil Salvesen"
- git config credential.helper "store --file=.git/credentials"
- git config --global push.default matching
- echo "https://${GH_TOKEN}:@github.com" > .git/credentials
- echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
- npm run release
- git status
- git push
branches:
  except:
  - "/^v[0-9]/"
env:
  global:
  - secure: UuBc0zADK4MZvia2Dui6vxx4d6wIWUp/7bL4iAIajxqpzPUr+PgfztV7r11N8So2W/xNn4g/QiAlDDHSW/ilNhEcQr1KCFE3SO2yQDOBXlrr/X8faWU38J6Q0tcBHM1RLtdAjY9jir62WOl+IGfSdSLGAo/TwjtuCUKysBiAlsA=
deploy:
  provider: npm
  email: andersems@gmail.com
  api_key:
    secure: H9dXujblZDaZ3BNwvPp/rwAT+g9de/pyVlchdNEFrUIQPOMb/ECU8CUuc0InAEb09nx8NBgFCMNfa6sJ+YAntYIxdMw/X4qOqA82eNgpvp/EhBSDHRkNeIxZNzbTVN1DaVLiwIbdA6Q7hiu6lY2C93RCaN37sw7e9IUv5BCtKbI=
  on:
    repo: andersem/urlconcat
    branch: master
    node: '6.9'
